### ISSUE TITLE
DCBorderedTextView Remove Done Button

### ISSUE THREAD

**Issue by yarodevuci** [andrew8712/DCKit#4]
How to remove annoying done button above the keyboard? 
![simulator screen shot dec 4 2016 3 28 09 pm](https://cloud.githubusercontent.com/assets/13408859/20870088/60d164f4-ba36-11e6-95f1-453b881730d4.png)

**Comment by agordeev** [comment]
There is a property called `showToolbar`. It's `true` by default. Just set it to `false`.

Another easy way is to change the property with using the attributes inspector. Switch `Show Toolbar` from `Default` to `Off`.

**Comment by yarodevuci** [comment]
Thank you! That helped. Did not even noticed that functionality
