### ISSUE TITLE
Button Pressed Background not working

### ISSUE THREAD

**Issue by yarodevuci** [andrew8712/DCKit#5]
Hi, when I set button pressed or highlighted in DCRoundedButton colors never changing 
Is that a bug?

**Comment by agordeev** [comment]
Can you please clarify the issue? Are you setting it programmatically?

**Comment by yarodevuci** [comment]
@andrew8712 Hi, so I am using Attributes Inspector. **Base Button** section. When I use color for Selected background it never shows that color if I pressed the button

**Comment by agordeev** [comment]
When you presses the button it goes to highlighted state, not selected. To set a selected state you need to explicitly set button's `isSelected` property to `true`.

**Comment by yarodevuci** [comment]
Oh I see. Thanks!

**Comment by yarodevuci** [comment]
Selected button background color covers the title color.. What to do ?

**Comment by agordeev** [comment]
Just change `selectedTextColor` to a different color.

**Comment by yarodevuci** [comment]
@agordeev Found the problem, I had to select Custom type for button
