### ISSUE TITLE
Updated Xcode project won't compile

### ISSUE THREAD

**Issue by yarodevuci** [andrew8712/DCKit#7]
Please help, after updating the Xcode from App Store, I have tons of errors in DCPlaceholderTextView, DCBaseTextField

**Comment by agordeev** [comment]
Simply update the pod to version `1.0.9`. I've implemented Swift 4 support recently.

**Comment by kcbandari** [comment]
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font' Displays updating my xCode

**Comment by agordeev** [comment]
Also make sure your project is updated to Swift 4.

**Comment by yarodevuci** [comment]
@agordeev you speak RU right?

**Comment by yarodevuci** [comment]
@agordeev do you still have Swift 3 support?

**Comment by agordeev** [comment]
>@agordeev you speak RU right?

Right.

>@agordeev do you still have Swift 3 support?

Sure, just fall back to version `1.0.7`.

**Comment by yarodevuci** [comment]
@agordeev а как это сделать через pods?

**Comment by agordeev** [comment]
pod 'DCKit', '1.0.7'

More examples here: https://guides.cocoapods.org/using/the-podfile.html

**Comment by yarodevuci** [comment]
@agordeev Спасибо большое
