### ISSUE TITLE
Compiler Errors for XCode 9.0.1 and Swift 4

### ISSUE THREAD

**Issue by jasontwong** [andrew8712/DCKit#8]
I'm getting swift compiler errors with version `1.0.9` from cocoapods. Attached is screenshot of the errors when building.

<img width="263" alt="screen shot 2017-10-19 at 11 21 00 am" src="https://user-images.githubusercontent.com/1128472/31778878-c539bca0-b4bf-11e7-9e83-a02decdd7541.png">

**Comment by yarodevuci** [comment]
Try 1.0.7 pod version

**Comment by agordeev** [comment]
It seems you haven't migrated your project to Swift 4 yet. As @yarodevuci said, try `1.0.7`
